services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ./knowledge_base:/app/rag/knowledge_base

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/rag/query
    depends_on:
      - backend